[package]
name = "stacks-wars-be"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8.4", features = ["ws"]}
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
